### ISSUE TITLE
methods and definition for loginprofile

### ISSUE THREAD

**Issue by mfutech** [serverworks/stratus#2]
Hi, 
I cannot seems to find a ways to define a loginprofile for a user.
Will loginprofile be supported in a future release ?
thanks,
M.

**Comment by juno** [comment]
Unfortunately v1.0.1 is not supported for loginprofile APIs.
We will support loginprofile and release next version within a month.

thanks,
juno

**Comment by juno** [comment]
Now v1.1.0 supports loginprofile API, yay!
